'use client';
import {useEffect,useState,useRef} from 'react';
import {fileApi} from '../../lib/r2-client';
export const workspaceApi=(db,b)=>fileApi(db,b,'/api/workspace');
export function Notice({error,message}){return <>{error&&<p className="loginError" role="alert">{error}</p>}{message&&<p className="saveMsg" role="status">{message}</p>}</>}
export function Dialog({title,onClose,children}){
 const ref=useRef(null);useEffect(()=>{const prior=document.activeElement;ref.current.showModal();return()=>prior?.focus?.()},[]);
 return <dialog ref={ref} className="uxDialog" onCancel={e=>{e.preventDefault();onClose()}}><div className="modalHead"><h2>{title}</h2><button type="button" className="secondary" aria-label="Fechar" onClick={onClose}>×</button></div>{children}</dialog>;
}
export function Thread({supabase,clientId,subjectId,subjectType='material',agency=false,slides=false,onNote}){
 const [data,setData]=useState({comments:[],assets:[]}),[body,setBody]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[progress,setProgress]=useState('');
 const request=b=>workspaceApi(supabase,{...b,clientId,subjectId,subjectType});
 async function load(){try{setData(await request({action:'thread'}))}catch(e){setError(e.message)}}
 useEffect(()=>{setData({comments:[],assets:[]});setBody('');setError('');load()},[clientId,subjectId]);
 async function comment(){setBusy(true);setError('');try{await request({action:'comment',body});setBody('');await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function upload(e,purpose){const files=Array.from(e.target.files||[]);if(!files.length)return;setBusy(true);setError('');try{for(let i=0;i<files.length;i++){const f=files[i];setProgress(`Enviando ${i+1} de ${files.length}…`);const ticket=await request({action:'initAsset',name:f.name,mime:f.type||(f.name.endsWith('.zip')?'application/zip':''),size:f.size,purpose});const res=await fetch(ticket.url,{method:'PUT',headers:{'Content-Type':f.type||'application/zip'},body:f});if(!res.ok)throw new Error('Falha no envio. Confira sua conexão e tente novamente.');await request({action:'finishAsset',assetId:ticket.id})}await load()}catch(e){setError(e.message)}finally{setBusy(false);setProgress('');e.target.value=''}}
 async function open(f){setError('');const w=window.open('about:blank','_blank');if(w)w.opener=null;try{const {url}=await request({action:'readAsset',assetId:f.id});if(w)w.location.href=url;else window.location.assign(url)}catch(e){w?.close();setError(e.message)}}
 return <section className="uxThread"><h3>{slides?'Imagens do carrossel e conversa':'Comentários e anexos'}</h3>
 {data.assets.filter(f=>f.purpose==='slide').length>0&&<div className="uxSlides">{data.assets.filter(f=>f.purpose==='slide').map((f,i)=><AssetPreview key={f.id} file={f} request={request} index={i}/>)}</div>}
 {slides&&agency&&<label className="secondary uploadBtn">Adicionar imagens em ordem<input type="file" multiple accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={e=>upload(e,'slide')}/></label>}
 {data.decisions?.length>0&&<details><summary>Histórico de aprovação</summary>{data.decisions.map(d=><p key={d.id}><b>{({sent:'Enviado para aprovação',approved:'Aprovado',changes_requested:'Ajustes solicitados',delivered:'Entregue'})[d.event]||d.event}</b> · {d.author_name} · {new Date(d.created_at).toLocaleString('pt-BR')}{d.note&&<span> — {d.note}</span>}</p>)}</details>}{data.comments.map(c=><div className="uxComment" key={c.id}><small>{c.author_name} · {new Date(c.created_at).toLocaleString('pt-BR')}</small><p>{c.body}</p></div>)}
 {data.assets.filter(f=>f.purpose!=='slide').map(f=><button className="uxAttachment" key={f.id} onClick={()=>open(f)}>↗ {f.file_name} <small>{(f.file_size/1048576).toFixed(1)} MB</small></button>)}
 <label>Escreva sua mensagem<textarea rows={4} maxLength={20000} placeholder="Descreva sua ideia ou o que gostaria de alterar…" value={body} onChange={e=>{setBody(e.target.value);onNote?.(e.target.value)}}/></label>
 <div className="uxActions"><button className="primary" onClick={comment} disabled={busy||!body.trim()}>Enviar comentário</button><label className="secondary uploadBtn">Anexar referência<input type="file" multiple accept="image/jpeg,image/png,image/webp,application/pdf,video/mp4,video/webm,.zip,.docx" disabled={busy} onChange={e=>upload(e,'reference')}/></label></div><small>Texto e anexos são independentes. Até 100 MB por anexo.</small>{progress&&<p role="status">{progress}</p>}<Notice error={error}/>
 </section>;
}
function AssetPreview({file,request,index}){const [url,setUrl]=useState(''),[error,setError]=useState('');useEffect(()=>{let active=true;request({action:'readAsset',assetId:file.id,preview:true}).then(r=>{if(active)setUrl(r.url)}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[file.id]);return <figure>{url&&<img src={url} alt={`${index+1}. ${file.file_name}`}/>}<figcaption>{index+1}. {file.file_name}</figcaption>{error&&<small>{error}</small>}</figure>}
export default function ClientWorkspace({supabase,client,section='references',readOnly=false}){
 const branding=section==='branding';const [items,setItems]=useState([]),[agency,setAgency]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState(''),[query,setQuery]=useState(''),[category,setCategory]=useState(''),[selected,setSelected]=useState(null),[editing,setEditing]=useState(null),[busy,setBusy]=useState(false),[history,setHistory]=useState(null);
 const request=b=>workspaceApi(supabase,{...b,clientId:client.id,section});
 async function load(){setLoading(true);try{const r=await request({action:'list'});setItems(r.items);setAgency(r.agency)}catch(e){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{setSelected(null);setEditing(null);setQuery('');load()},[client.id,section]);
 async function save(e){e.preventDefault();setBusy(true);setError('');try{const r=await request({action:'save',...editing,updatedAt:editing.updated_at});setEditing(null);setSelected({...r.item,can_edit:true});setMessage('Salvo. Você pode anexar arquivos ou continuar escrevendo.');await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
 const filtered=items.filter(i=>(!category||i.category===category)&&`${i.title} ${i.body}`.toLowerCase().includes(query.toLowerCase()));
 return <section className="uxWorkspace"><div className="sectionHead"><div><small>{branding?'IDENTIDADE DO CLIENTE':'BANCO DE IDEIAS'}</small><h2>{branding?'Branding':'Referências'}</h2><p>{branding?'Tudo para criar com a personalidade desta marca.':'Uma ideia pode começar com uma frase. Links e anexos são opcionais.'}</p></div>{(!branding||agency)&&<button className="primary" onClick={()=>{setSelected(null);setEditing({title:'',body:'',link:'',category:branding?'Marca':'Ideia',shared:!agency,state:'Para avaliar'})}}>{branding?'+ Adicionar material':'+ Escrever ideia'}</button>}</div>
 <div className="uxFilters"><input aria-label="Buscar referências" placeholder="Buscar no título ou texto…" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Filtrar categoria" value={category} onChange={e=>setCategory(e.target.value)}><option value="">Todas as categorias</option>{[...new Set(items.map(i=>i.category))].map(c=><option key={c}>{c}</option>)}</select><span>{filtered.length} itens</span></div><Notice error={error} message={message}/>
 {loading?<p role="status">Carregando seu espaço…</p>:!filtered.length?<div className="uxEmpty"><h3>{query||category?'Nenhum resultado neste filtro.':branding?'A identidade da marca começa aqui.':'Guarde a próxima boa ideia.'}</h3><p>{branding?'Registre as cores, fontes, orientações e os arquivos da marca.':'Escreva um texto livre. Depois, se quiser, acrescente imagens e links.'}</p></div>:<div className="uxCards">{filtered.map(item=><button className="uxIdea" key={item.id} onClick={()=>{setSelected(item);setHistory(null);setMessage('')}}><div className="uxActions"><span className="uxChip">{item.category}</span><small>{item.shared?'Compartilhada':'Interna'}</small></div><h3>{item.title}</h3><p>{item.body}</p><footer><span>{item.state}</span><small>{new Date(item.updated_at).toLocaleDateString('pt-BR')}</small></footer></button>)}</div>}
 {editing&&<Dialog title={branding?'Material da marca':'Escrever ideia'} onClose={()=>{if(!busy&&confirm('Fechar sem salvar este texto?'))setEditing(null)}}><form onSubmit={save}><label>Título opcional<input maxLength={200} value={editing.title} onChange={e=>setEditing({...editing,title:e.target.value})}/></label><label>{branding?'Cores, fontes, tom de voz e orientações':'Sua ideia'}<textarea autoFocus rows={10} maxLength={100000} value={editing.body} onChange={e=>setEditing({...editing,body:e.target.value})} placeholder="Pode apenas escrever aqui. Nenhum anexo é obrigatório."/></label><label>Link opcional<input type="url" value={editing.link} onChange={e=>setEditing({...editing,link:e.target.value})}/></label><div className="formGrid"><label>Categoria<select value={editing.category} onChange={e=>setEditing({...editing,category:e.target.value})}>{(branding?['Marca','Logo','Cores','Fontes','Tom de voz','Manual']:['Ideia','Post','Carrossel','Stories','Vídeo','Campanha','Referência visual']).map(x=><option key={x}>{x}</option>)}</select></label><label>Status<select value={editing.state} onChange={e=>setEditing({...editing,state:e.target.value})}>{['Para avaliar','Selecionada','Já utilizada'].map(x=><option key={x}>{x}</option>)}</select></label></div>{agency&&<label className="checkLine"><input type="checkbox" checked={editing.shared} onChange={e=>setEditing({...editing,shared:e.target.checked})}/>Compartilhar com o cliente</label>}<Notice error={error}/><button className="primary" disabled={busy}>{busy?'Salvando…':'Salvar texto'}</button></form></Dialog>}
 {selected&&!editing&&<Dialog title={selected.title} onClose={()=>setSelected(null)}><div className="uxActions"><span className="uxChip">{selected.category}</span><span>{selected.shared?'Compartilhada com o cliente':'Somente equipe'}</span></div><p className="uxFullText">{selected.body}</p>{selected.link&&<a href={selected.link} target="_blank" rel="noopener noreferrer">Abrir referência ↗</a>}<div className="uxActions">{(agency||selected.can_edit)&&<button className="secondary" onClick={()=>setEditing({...selected})}>Editar texto</button>}{agency&&!branding&&<button className="primary" disabled={busy} onClick={async()=>{setBusy(true);try{await request({action:'convert',id:selected.id});setMessage('Conteúdo criado em Produção, com esta referência no briefing.');setSelected(null)}catch(e){setError(e.message)}finally{setBusy(false)}}}>Transformar em conteúdo</button>}</div><Thread supabase={supabase} clientId={client.id} subjectId={selected.id} agency={agency}/>{agency&&<details onToggle={async e=>{if(e.currentTarget.open&&history===null){try{setHistory((await request({action:'materialHistory',subjectId:selected.id,subjectType:'material'})).history)}catch(err){setError(err.message)}}}}><summary>Histórico do texto</summary>{history?.length?history.map(h=><div key={h.id} className="uxComment"><small>{new Date(h.created_at).toLocaleString('pt-BR')}</small><h4>{h.snapshot.title}</h4><p>{h.snapshot.body}</p></div>):<p>Nenhuma versão anterior.</p>}</details>}<Notice error={error}/></Dialog>}
 </section>;
}
