'use client';
import {useEffect,useState} from 'react';
import {workspaceApi,Thread,Dialog,Notice} from './ClientWorkspace';
import {fileApi} from '../../lib/r2-client';
import {productionLabel} from '../../lib/production-policy.mjs';
const label=s=>({adjustments:'Ajustes solicitados',internal_review:'Revisão interna',briefing:'Briefing'})[s]||productionLabel(s);
export function Caption({supabase,clientId,version,agency}){const [body,setBody]=useState(version.caption||''),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);return <section className="uxCaption"><h3>Legenda da versão {version.version_number}</h3>{agency&&version.status==='draft'?<><textarea rows={5} maxLength={20000} value={body} onChange={e=>{setBody(e.target.value);setMessage('')}} placeholder="Texto que acompanha a publicação…"/><button className="secondary" disabled={busy} onClick={async()=>{setBusy(true);try{await workspaceApi(supabase,{action:'caption',clientId,subjectType:'version',subjectId:version.id,body});setMessage('Legenda salva.')}catch(e){setError(e.message)}finally{setBusy(false)}}}>Salvar legenda</button></>:<p className="uxFullText">{version.caption||'Sem legenda nesta versão.'}</p>}<Notice error={error} message={message}/></section>}
function Preview({supabase,v,compact=false}){const [url,setUrl]=useState(''),[error,setError]=useState('');useEffect(()=>{let active=true;if(v)fileApi(supabase,{action:'read',versionId:v.id}).then(r=>{if(active)setUrl(r.url)}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[v?.id]);if(!v)return <div className="uxPreview placeholder">Em criação</div>;return <div className={'uxPreview '+(compact?'compact':'')}>{url?(v.mime_type?.startsWith('image/')?<img src={url} alt={v.file_name}/>:v.mime_type?.startsWith('video/')?<video src={url} controls={!compact} preload="metadata"/>:compact?<span>{v.file_name}</span>:<a href={url} target="_blank" rel="noopener noreferrer">Abrir {v.file_name}</a>):<span>{error||'Carregando prévia…'}</span>}</div>}
export default function ContentBoard({supabase,client,ctx,renderDetail,onNew,onlyReview=false}){
 const [items,setItems]=useState([]),[agency,setAgency]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[query,setQuery]=useState(''),[month,setMonth]=useState(''),[status,setStatus]=useState(onlyReview?'with_client':''),[layout,setLayout]=useState('grid'),[selected,setSelected]=useState(null),[note,setNote]=useState(''),[schedule,setSchedule]=useState('');
 const request=b=>workspaceApi(supabase,{...b,clientId:client?.id,organizationId:ctx?.organization?.id||client?.organization_id});
 async function load(){setLoading(true);setError('');try{const r=await request({action:'contents'});setItems(r.items);setAgency(r.agency)}catch(e){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[client?.id,ctx?.organization?.id]);
 const target=typeof window!=='undefined'?new URLSearchParams(window.location.search).get('approval'):null;
 const filtered=items.filter(d=>(!status||d.status===status)&&(!month||(d.publish_date||d.due_date||d.created_at).slice(0,7)===month)&&`${d.title} ${d.clients?.name} ${d.type}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>Number(b.id===target)-Number(a.id===target));
 const latest=d=>[...(d.demand_versions||[])].sort((a,b)=>b.version_number-a.version_number)[0];
 function open(d){setSelected(d);setNote('');setSchedule(d.publish_date||'')}
 async function decide(action){setBusy(true);setError('');try{await fileApi(supabase,{action,demandId:selected.id,versionId:latest(selected).id,note},'/api/production');setSelected(null);await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
 function card(d){const v=latest(d);return <button key={d.id} className="uxContentCard" onClick={()=>open(d)}><Preview supabase={supabase} v={v} compact/><div className="uxCardBody"><small>{d.clients?.name||client?.name} · {d.type}</small><h3>{d.title}</h3><span className={'uxStatus '+d.status}>{label(d.status)}</span><footer>{d.publish_date?`Publicação: ${d.publish_date.split('-').reverse().join('/')}`:'Publicação a definir'}<span>{v?`V${v.version_number}`:'Rascunho'}</span></footer></div></button>}
 if(selected&&agency&&renderDetail)return <><button className="back" onClick={()=>{setSelected(null);load()}}>← Todos os conteúdos</button>{renderDetail(selected,()=>{setSelected(null);load()})}</>;
 return <section className="uxBoard"><div className="sectionHead"><div><small>{agency?'PRODUÇÃO ORGANIZADA':'SEU ESPAÇO DE APROVAÇÃO'}</small><h2>{onlyReview?'Prontos para revisar':'Conteúdos e aprovações'}</h2><p>Cada conteúdo tem sua própria conversa, arquivos e decisão.</p></div>{onNew&&agency&&<button className="primary" onClick={onNew}>+ Novo conteúdo</button>}</div><div className="uxStats">{[['','Todos'],['with_client','Aguardando aprovação'],['adjustments','Com ajustes'],['approved','Aprovados']].map(([k,l])=><button key={k} onClick={()=>setStatus(k)} className={status===k?'active':''}><strong>{items.filter(d=>!k||d.status===k).length}</strong><span>{l}</span></button>)}</div><div className="uxFilters"><input placeholder="Buscar conteúdo ou cliente…" aria-label="Buscar conteúdo" value={query} onChange={e=>setQuery(e.target.value)}/><input aria-label="Mês da programação" type="month" value={month} onChange={e=>setMonth(e.target.value)}/><select aria-label="Status" value={status} onChange={e=>setStatus(e.target.value)}><option value="">Todos os status</option>{['in_production','internal_review','with_client','adjustments','approved','awaiting_scheduling','scheduled','posted','delivered'].map(s=><option key={s} value={s}>{label(s)}</option>)}</select>{month&&<button className="secondary" onClick={()=>setMonth('')}>Todos os meses</button>}{agency&&<div className="uxSegment"><button className={layout==='grid'?'active':''} onClick={()=>setLayout('grid')}>Cards</button><button className={layout==='kanban'?'active':''} onClick={()=>setLayout('kanban')}>Etapas</button></div>}</div><Notice error={error}/>{loading?<p role="status">Carregando conteúdos…</p>:!filtered.length?<div className="uxEmpty"><h3>Nenhum conteúdo neste filtro.</h3><p>Selecione outro mês ou status para consultar a programação.</p></div>:layout==='kanban'&&agency?<div className="uxKanban">{[...new Set(filtered.map(d=>d.status))].map(s=><section key={s}><h3>{label(s)} <small>{filtered.filter(d=>d.status===s).length}</small></h3>{filtered.filter(d=>d.status===s).map(card)}</section>)}</div>:<div className="uxContentGrid">{filtered.map(card)}</div>}
 {selected&&<Dialog title={selected.title} onClose={()=>{if(!busy)setSelected(null)}}>{latest(selected)&&<><Preview supabase={supabase} v={latest(selected)}/><Caption supabase={supabase} clientId={selected.client_id} version={latest(selected)} agency={agency}/><Thread supabase={supabase} clientId={selected.client_id} subjectId={latest(selected).id} subjectType="version" agency={agency}/>{!agency&&selected.status==='with_client'&&latest(selected).status==='sent_for_review'&&<section className="uxDecision"><h3>Sua decisão</h3><label>O que precisa ser alterado?<textarea value={note} maxLength={20000} rows={4} onChange={e=>setNote(e.target.value)} placeholder="Obrigatório ao solicitar ajustes. Anexe referências no espaço acima."/></label><div className="uxActions"><button className="primary" disabled={busy} onClick={()=>decide('approve')}>Aprovar conteúdo</button><button className="secondary" disabled={busy||!note.trim()} onClick={()=>decide('changes')}>Solicitar ajustes</button></div><p>A decisão vale para a versão {latest(selected).version_number}, incluindo a legenda.</p></section>}<details className="uxHistory"><summary>Versões anteriores ({Math.max(0,selected.demand_versions.length-1)})</summary>{selected.demand_versions.filter(v=>v.id!==latest(selected).id).sort((a,b)=>b.version_number-a.version_number).map(v=><section key={v.id}><h3>Versão {v.version_number} · {v.status}</h3><Preview supabase={supabase} v={v}/><p className="uxFullText">{v.caption}</p><Thread supabase={supabase} clientId={selected.client_id} subjectId={v.id} subjectType="version"/></section>)}</details></>}<Notice error={error}/></Dialog>}
 </section>;
}
export function ScheduleContent({supabase,demand}){const [date,setDate]=useState(demand.publish_date||''),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);return <div className="uxSchedule"><label>Previsão de publicação<input type="date" value={date} onChange={e=>{setDate(e.target.value);setMessage('')}}/></label><button className="secondary" disabled={busy} onClick={async()=>{setBusy(true);try{await workspaceApi(supabase,{action:'scheduleContent',clientId:demand.client_id,demandId:demand.id,date});setMessage('Data atualizada nos calendários do cliente e da agência.')}catch(e){setError(e.message)}finally{setBusy(false)}}}>Salvar data</button><Notice error={error} message={message}/></div>}
