'use client';
import {useEffect,useRef,useState} from 'react';
import {workspaceApi,Thread,Dialog,Notice} from './ClientWorkspace';
import {fileApi,uploadProduction} from '../../lib/r2-client';
import {productionLabel} from '../../lib/production-policy.mjs';
const label=s=>({adjustments:'Ajustes solicitados',internal_review:'Revisão interna',briefing:'Briefing'})[s]||productionLabel(s);

export function Caption({supabase,clientId,version,agency}){
 const [body,setBody]=useState(version.caption||''),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 return <section className="uxCaption"><h3>Legenda da versão {version.version_number}</h3>{agency&&version.status==='draft'?<><textarea rows={5} maxLength={20000} value={body} onChange={e=>{setBody(e.target.value);setMessage('')}} placeholder="Texto que acompanha a publicação…"/><button className="secondary" disabled={busy} onClick={async()=>{setBusy(true);try{await workspaceApi(supabase,{action:'caption',clientId,subjectType:'version',subjectId:version.id,body});setMessage('Legenda salva.')}catch(e){setError(e.message)}finally{setBusy(false)}}}>Salvar legenda</button></>:<p className="uxFullText">{version.caption||'Sem legenda nesta versão.'}</p>}<Notice error={error} message={message}/></section>;
}

function Preview({supabase,v,compact=false}){
 const [url,setUrl]=useState(''),[error,setError]=useState('');
 useEffect(()=>{let active=true;if(v)fileApi(supabase,{action:'read',versionId:v.id}).then(r=>{if(active)setUrl(r.url)}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[v?.id]);
 if(!v)return <div className="uxPreview placeholder">Em criação</div>;
 return <div className={'uxPreview '+(compact?'compact':'')}>{url?(v.mime_type?.startsWith('image/')?<img src={url} alt={v.file_name}/>:v.mime_type?.startsWith('video/')?<video src={url} controls={!compact} preload="metadata"/>:compact?<span>{v.file_name}</span>:<a href={url} target="_blank" rel="noopener noreferrer">Abrir {v.file_name}</a>):<span>{error||'Carregando prévia…'}</span>}</div>;
}

function ArtworkCard({d,v,supabase,agency,clientName,onOpen,onUploaded,onEdit,onMove}){
 const [uploading,setUploading]=useState(false),[progress,setProgress]=useState(0),[message,setMessage]=useState('');
 const controller=useRef(null);
 useEffect(()=>()=>controller.current?.abort(),[]);
 async function attach(event){
  const input=event.target,file=input.files?.[0];if(!file)return;
  const current=new AbortController();controller.current=current;setUploading(true);setProgress(0);setMessage('');
  try{const result=await uploadProduction(supabase,d.id,file,setProgress,current.signal);setMessage(`${result.fileName||file.name} anexado a este post.`);await onUploaded?.()}
  catch(error){setMessage(error.message)}
  finally{setUploading(false);controller.current=null;input.value=''}
 }
 return <article className="productionArtCard">
  <button className="uxContentCard" onClick={onOpen}><Preview supabase={supabase} v={v} compact/><div className="uxCardBody"><small>{d.type} · {d.clients?.name||clientName}</small><h3>{d.title}</h3><span className={'uxStatus '+d.status}>{label(d.status)}</span>{d.due_date&&<small>Prazo de produção: {d.due_date.split('-').reverse().join('/')}</small>}<p className="productionNext"><b>Próxima ação:</b> {d.status==='with_client'?(agency?'Cliente precisa aprovar':'Sua aprovação está pendente'):d.status==='approved'&&!d.publish_date?'Design precisa definir a publicação':d.status==='approved'?'Cliente aprovou · Design organiza a publicação':d.status==='internal_review'?'Revisão da equipe':d.status==='adjustments'?'Design precisa ajustar a arte':['scheduled','awaiting_scheduling'].includes(d.status)?'Design organiza a publicação':d.status==='posted'?'Publicado':'Design precisa produzir'}</p><footer>{d.publish_date?`Publicação: ${d.publish_date.split('-').reverse().join('/')}`:'Publicação a definir'}<span>{v?`V${v.version_number}`:'Sem anexo'}</span></footer>{d.approved_at&&<small className="approvedDate">Aprovado em {new Date(d.approved_at).toLocaleDateString('pt-BR')}</small>}</div></button>
  {agency&&<div className="artCardActions"><label className="secondary uploadBtn productionAttach">{uploading?`Enviando ${progress}%`:'Anexar foto ou PDF a este post'}<input type="file" accept=".pdf,.jpg,.jpeg,.png,application/pdf,image/jpeg,image/png" disabled={uploading} onChange={attach}/></label>{d.project_id&&<button className="artEdit" onClick={onEdit}>Editar arte</button>}{!d.project_id&&onMove&&<button className="artEdit" onClick={onMove}>Mover para projeto</button>}{uploading&&<button className="artEdit" onClick={()=>controller.current?.abort()}>Pausar</button>}</div>}
  {message&&<small className={uploading?'':'artUploadMessage'} role="status">{message}</small>}
 </article>;
}

export default function ContentBoard({supabase,client,ctx,renderDetail,onlyReview=false}){
 const [items,setItems]=useState([]),[projects,setProjects]=useState([]),[availableClients,setAvailableClients]=useState([]),[agency,setAgency]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[query,setQuery]=useState(''),[month,setMonth]=useState(''),[status,setStatus]=useState(onlyReview?'with_client':''),[selected,setSelected]=useState(null),[note,setNote]=useState(''),[expanded,setExpanded]=useState({}),[editor,setEditor]=useState(null),[form,setForm]=useState({}),[saving,setSaving]=useState(false);
 const request=b=>workspaceApi(supabase,{...b,clientId:client?.id,organizationId:ctx?.organization?.id||client?.organization_id});
 const projectRequest=b=>fileApi(supabase,{...b,clientId:client?.id||b.clientId,organizationId:ctx?.organization?.id||client?.organization_id},'/api/projects');
 async function load(){setLoading(true);setError('');try{const r=await request({action:'contents'});setItems(r.items);setProjects(r.projects||[]);setAgency(r.agency);if(!client&&ctx?.organization?.id){const {data,error:clientError}=await supabase.from('clients').select('id,name').eq('organization_id',ctx.organization.id).order('name');if(clientError)throw clientError;setAvailableClients(data||[])}}catch(e){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[client?.id,ctx?.organization?.id]);
 const target=typeof window!=='undefined'?new URLSearchParams(window.location.search).get('approval'):null;
 const filtered=items.filter(d=>(!status||d.status===status)&&(!month||(d.publish_date||d.due_date||d.created_at).slice(0,7)===month)&&`${d.title} ${d.project?.title||''} ${d.clients?.name} ${d.type}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>Number(b.id===target)-Number(a.id===target));
 const latest=d=>[...(d.demand_versions||[])].sort((a,b)=>b.version_number-a.version_number)[0];
 function open(d){setSelected(d);setNote('')}
 async function decide(action){setBusy(true);setError('');try{await fileApi(supabase,{action,demandId:selected.id,versionId:latest(selected).id,note},'/api/production');setSelected(null);await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
 function nextAction(d){if(d.status==='with_client')return agency?'Cliente precisa aprovar':'Sua aprovação está pendente';if(d.status==='approved'&&!d.publish_date)return 'Design precisa definir a publicação';if(d.status==='approved')return 'Cliente aprovou · Design organiza a publicação';if(d.status==='internal_review')return 'Revisão da equipe';if(d.status==='adjustments')return 'Design precisa ajustar a arte';if(['scheduled','awaiting_scheduling'].includes(d.status))return 'Design organiza a publicação';if(d.status==='posted')return 'Publicado';return 'Design precisa produzir';}
 function card(d){const v=latest(d);return <ArtworkCard key={d.id} d={d} v={v} supabase={supabase} agency={agency} clientName={client?.name} onOpen={()=>open(d)} onUploaded={load} onEdit={()=>{setEditor({kind:'art',projectId:d.project_id,demandId:d.id});setForm({title:d.title,type:d.type,briefing:d.briefing||'',notes:d.notes||'',responsibleName:d.responsible_name||'',dueDate:d.due_date||''})}} onMove={!d.project_id&&projects.some(p=>p.client_id===d.client_id)?()=>{setEditor({kind:'move',demandId:d.id,clientId:d.client_id});setForm({targetProjectId:projects.find(p=>p.client_id===d.client_id)?.id||''})}:null}/>}
 const projectCards=projects.map(project=>({project,contents:filtered.filter(d=>d.project_id===project.id)})).filter(({project,contents})=>!query||project.title.toLowerCase().includes(query.toLowerCase())||contents.length);
 const loose=filtered.filter(d=>!d.project_id);
 async function saveProject(e){e.preventDefault();setSaving(true);setError('');try{await projectRequest({action:editor.projectId?'update':'create',...(editor.projectId?{projectId:editor.projectId}:{}),clientId:form.clientId,title:form.title,description:form.description});setEditor(null);await load()}catch(e){setError(e.message)}finally{setSaving(false)}}
 async function saveArt(e){e.preventDefault();setSaving(true);setError('');try{await projectRequest({action:editor.demandId?'updateArt':'createArt',projectId:editor.projectId,demandId:editor.demandId,title:form.title,type:form.type,briefing:form.briefing,notes:form.notes,responsibleName:form.responsibleName,dueDate:form.dueDate});setEditor(null);await load()}catch(e){setError(e.message)}finally{setSaving(false)}}
 async function saveMove(e){e.preventDefault();setSaving(true);setError('');try{await projectRequest({action:'moveArt',projectId:form.targetProjectId,demandId:editor.demandId});setEditor(null);await load()}catch(e){setError(e.message)}finally{setSaving(false)}}
 async function removeProject(project){if(!window.confirm(`Excluir o projeto “${project.title}”? As artes e os arquivos serão preservados e continuarão disponíveis sem projeto.`))return;setBusy(true);try{await projectRequest({action:'delete',projectId:project.id});await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
 if(selected&&agency&&renderDetail)return <><button className="back" onClick={()=>{setSelected(null);load()}}>← Todos os projetos</button>{renderDetail(selected,()=>{setSelected(null);load()})}</>;
 return <section className="uxBoard productionBoard">
  <div className="sectionHead"><div><small>{agency?'PRODUÇÃO ORGANIZADA':'SEU ESPAÇO DE APROVAÇÃO'}</small><h2>{onlyReview?'Prontos para revisar':client?'Projetos e conteúdos':'Conteúdos e aprovações'}</h2><p>{client?'Cada projeto reúne suas artes, textos, arquivos e aprovações.':'Em cada arte, veja quem precisa agir e qual é o próximo passo.'}</p></div>{agency&&!onlyReview&&<button className="primary" onClick={()=>{setEditor({kind:'project'});setForm({title:'',description:'',clientId:client?.id||''})}}>+ Novo projeto</button>}</div>
  <div className="uxStats">{[['','Todos'],['with_client','Aguardando aprovação'],['adjustments','Com ajustes'],['approved','Aprovados']].map(([k,l])=><button key={k} onClick={()=>setStatus(k)} className={status===k?'active':''}><strong>{items.filter(d=>!k||d.status===k).length}</strong><span>{l}</span></button>)}</div>
  <div className="uxFilters"><input placeholder="Buscar projeto, arte ou cliente…" aria-label="Buscar projeto, arte ou cliente" value={query} onChange={e=>setQuery(e.target.value)}/><input aria-label="Mês da programação" type="month" value={month} onChange={e=>setMonth(e.target.value)}/><select aria-label="Status" value={status} onChange={e=>setStatus(e.target.value)}><option value="">Todos os status</option>{['in_production','internal_review','with_client','adjustments','approved','awaiting_scheduling','scheduled','posted','delivered'].map(s=><option key={s} value={s}>{label(s)}</option>)}</select>{month&&<button className="secondary" onClick={()=>setMonth('')}>Todos os meses</button>}</div>
  <Notice error={error}/>
  {loading?<p role="status">Carregando projetos…</p>:!projectCards.length&&!loose.length?<div className="uxEmpty"><h3>Nenhum projeto por aqui ainda.</h3><p>Crie um projeto e adicione uma arte com briefing, referências e arquivos.</p></div>:<div className="projectGrid">
   {projectCards.map(({project,contents})=><article key={project.id} className="productionProject"><div className="projectHead"><button className="projectToggle" aria-expanded={!!expanded[project.id]} onClick={()=>setExpanded(x=>({...x,[project.id]:!x[project.id]}))}><span className="projectIcon">▣</span><span><small>PROJETO · {contents.length} {contents.length===1?'ARTE':'ARTES'}</small><strong>{project.title}</strong><em>{project.description||'Organize aqui textos, arquivos e aprovações.'}</em></span><span className="projectChevron">{expanded[project.id]?'−':'+'}</span></button>{agency&&<div className="projectActions"><button className="secondary" onClick={()=>{setEditor({kind:'project',projectId:project.id});setForm({title:project.title,description:project.description||''})}}>Editar projeto</button><button className="secondary dangerText" disabled={busy} onClick={()=>removeProject(project)}>Excluir</button></div>}</div>{expanded[project.id]&&<div className="projectContents">{agency&&<button className="primary addArt" onClick={()=>{setEditor({kind:'art',projectId:project.id});setForm({title:'',type:'Criativo estático',briefing:'',notes:'',responsibleName:'',dueDate:''})}}>+ Adicionar arte</button>}{contents.map(card)}{!contents.length&&<p className="projectEmpty">Este projeto ainda não tem artes. Adicione a primeira para iniciar a produção.</p>}</div>}</article>)}
   {loose.length>0&&<article className="productionProject legacyProject"><div className="projectHead"><button className="projectToggle" aria-expanded={!!expanded.loose} onClick={()=>setExpanded(x=>({...x,loose:!x.loose}))}><span className="projectIcon">▣</span><span><small>CONTEÚDOS EXISTENTES · {loose.length} {loose.length===1?'ARTE':'ARTES'}</small><strong>Sem projeto</strong><em>Conteúdos antigos preservados durante a organização.</em></span><span className="projectChevron">{expanded.loose?'−':'+'}</span></button></div>{expanded.loose&&<div className="projectContents">{loose.map(card)}</div>}</article>}
  </div>}
  {selected&&<Dialog title={selected.title} onClose={()=>{if(!busy)setSelected(null)}}>{latest(selected)&&<><Preview supabase={supabase} v={latest(selected)}/><Caption supabase={supabase} clientId={selected.client_id} version={latest(selected)} agency={agency}/><Thread supabase={supabase} clientId={selected.client_id} subjectId={latest(selected).id} subjectType="version" agency={agency}/>{!agency&&selected.status==='with_client'&&latest(selected).status==='sent_for_review'&&<section className="uxDecision"><h3>Sua decisão</h3><label>O que precisa ser alterado?<textarea value={note} maxLength={20000} rows={4} onChange={e=>setNote(e.target.value)} placeholder="Obrigatório ao solicitar ajustes. Anexe referências no espaço acima."/></label><div className="uxActions"><button className="primary" disabled={busy} onClick={()=>decide('approve')}>Aprovar conteúdo</button><button className="secondary" disabled={busy||!note.trim()} onClick={()=>decide('changes')}>Solicitar ajustes</button></div><p>A decisão vale para a versão {latest(selected).version_number}, incluindo a legenda.</p></section>}<details className="uxHistory"><summary>Versões anteriores ({Math.max(0,selected.demand_versions.length-1)})</summary>{selected.demand_versions.filter(v=>v.id!==latest(selected).id).sort((a,b)=>b.version_number-a.version_number).map(v=><section key={v.id}><h3>Versão {v.version_number} · {v.status}</h3><Preview supabase={supabase} v={v}/><p className="uxFullText">{v.caption}</p><Thread supabase={supabase} clientId={selected.client_id} subjectId={v.id} subjectType="version"/></section>)}</details></>}<Notice error={error}/></Dialog>}
  {editor&&<Dialog title={editor.kind==='project'?(editor.projectId?'Editar projeto':'Novo projeto'):editor.kind==='move'?'Mover arte para projeto':editor.demandId?'Editar arte':'Adicionar arte'} onClose={()=>{if(!saving)setEditor(null)}}><form className="projectForm" onSubmit={editor.kind==='project'?saveProject:editor.kind==='move'?saveMove:saveArt}>{editor.kind==='move'?<label>Projeto<select required value={form.targetProjectId||''} onChange={e=>setForm(x=>({...x,targetProjectId:e.target.value}))}>{projects.filter(p=>p.client_id===editor.clientId).map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select></label>:<>{editor.kind==='project'&&!client&&<label>Cliente<select required value={form.clientId||''} onChange={e=>setForm(x=>({...x,clientId:e.target.value}))}><option value="">Selecione o cliente</option>{availableClients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>}<label>{editor.kind==='project'?'Nome do projeto':'Nome da arte'}<input required autoFocus maxLength={200} value={form.title||''} onChange={e=>setForm(x=>({...x,title:e.target.value}))}/></label></>}{editor.kind==='project'?<label>Descrição do projeto<textarea rows={4} maxLength={10000} value={form.description||''} onChange={e=>setForm(x=>({...x,description:e.target.value}))} placeholder="Objetivo, campanha ou contexto geral"/></label>:editor.kind==='art'?<><label>Formato<select value={form.type||''} onChange={e=>setForm(x=>({...x,type:e.target.value}))}><option>Criativo estático</option><option>Carrossel</option><option>Stories</option><option>Vídeo / Reel</option><option>Outro</option></select></label><label>Briefing / texto<textarea rows={5} maxLength={20000} value={form.briefing||''} onChange={e=>setForm(x=>({...x,briefing:e.target.value}))} placeholder="Escreva o conteúdo, orientações e referências para a arte"/></label><label>Observações internas<textarea rows={3} maxLength={20000} value={form.notes||''} onChange={e=>setForm(x=>({...x,notes:e.target.value}))}/></label><label>Responsável<input value={form.responsibleName||''} onChange={e=>setForm(x=>({...x,responsibleName:e.target.value}))} placeholder="Quem está produzindo?"/></label><label>Prazo de produção<input type="date" value={form.dueDate||''} onChange={e=>setForm(x=>({...x,dueDate:e.target.value}))}/></label><p>Fotos e PDFs podem ser anexados depois, dentro do card desta arte. A data de publicação fica com o Design após a aprovação.</p></>:null}{error&&<Notice error={error}/>}<div className="modalActions"><button type="button" className="secondary" onClick={()=>setEditor(null)}>Cancelar</button><button className="primary" disabled={saving}>{saving?'Salvando…':editor.kind==='move'?'Mover arte':'Salvar'}</button></div></form></Dialog>}
 </section>;
}

export function ScheduleContent({supabase,demand}){const [date,setDate]=useState(demand.publish_date||''),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);return <div className="uxSchedule"><label>Previsão de publicação<input type="date" value={date} onChange={e=>{setDate(e.target.value);setMessage('')}}/></label><button className="secondary" disabled={busy} onClick={async()=>{setBusy(true);try{await workspaceApi(supabase,{action:'scheduleContent',clientId:demand.client_id,demandId:demand.id,date});setMessage('Data atualizada nos calendários do cliente e da agência.')}catch(e){setError(e.message)}finally{setBusy(false)}}}>Salvar data</button><Notice error={error} message={message}/></div>}
