'use client';
import {useEffect,useState,useRef} from 'react';
import {workspaceApi,Dialog,Notice} from './ClientWorkspace';
import {EVENT_TYPES,localInput,brazilISO} from '../../lib/workspace-policy.mjs';
const dayKey=date=>new Intl.DateTimeFormat('sv-SE',{timeZone:'America/Sao_Paulo'}).format(new Date(date));
const clock=date=>new Date(date).toLocaleTimeString('pt-BR',{timeZone:'America/Sao_Paulo',hour:'2-digit',minute:'2-digit'});
function color(id){let n=0;for(const ch of id||'interno')n=(n*31+ch.charCodeAt(0))%360;return `hsl(${n} 42% 37%)`}
export default function UnifiedCalendar({supabase,ctx,client=null}){
 const [data,setData]=useState({events:[],posts:[],team:[],clients:[],agency:false}),[error,setError]=useState(''),[loading,setLoading]=useState(true),[month,setMonth]=useState(()=>dayKey(new Date()).slice(0,7)),[view,setView]=useState('month'),[kind,setKind]=useState(''),[customer,setCustomer]=useState(''),[member,setMember]=useState(''),[edit,setEdit]=useState(null),[busy,setBusy]=useState(false);
 const loadSequence=useRef(0);
 const request=b=>workspaceApi(supabase,{...b,clientId:client?.id,organizationId:ctx.organization.id});
 async function load(){const requestNumber=++loadSequence.current;setLoading(true);setError('');const start=view==='month'?month+'-01':dayKey(new Date());const date=new Date(start+'T12:00:00-03:00');if(view==='month')date.setUTCMonth(date.getUTCMonth()+1);else date.setUTCDate(date.getUTCDate()+(view==='today'?1:7));try{const result=await request({action:'events',from:start,to:dayKey(date)});if(requestNumber===loadSequence.current)setData(result)}catch(e){if(requestNumber===loadSequence.current)setError(e.message)}finally{if(requestNumber===loadSequence.current)setLoading(false)}}
 useEffect(()=>{load()},[client?.id,ctx.organization.id,month,view]);
 const events=[...data.events,...data.posts.map(p=>({id:'post-'+p.id,title:p.title,client_id:p.client_id,clients:p.clients,kind:'post',starts_at:p.publish_date+'T12:00:00-03:00',ends_at:p.publish_date+'T12:00:00-03:00',dateOnly:true,fromContent:true,status:'scheduled',member_ids:[]}))].filter(e=>e.status!=='cancelled'&&(!kind||e.kind===kind)&&(!customer||e.client_id===customer)&&(!member||e.member_ids?.includes(member))).sort((a,b)=>new Date(a.starts_at)-new Date(b.starts_at));
 const today=dayKey(new Date()),weekEnd=new Date(today+'T12:00:00-03:00');weekEnd.setDate(weekEnd.getDate()+7);
 const visible=events.filter(e=>view==='month'?dayKey(e.starts_at).slice(0,7)<=month&&dayKey(e.ends_at).slice(0,7)>=month:view==='today'?dayKey(e.starts_at)===today:dayKey(e.starts_at)>=today&&dayKey(e.starts_at)<dayKey(weekEnd));
 const [year,mo]=month.split('-').map(Number),first=new Date(year,mo-1,1).getDay(),days=new Date(year,mo,0).getDate();
 function newEvent(day=today){setError('');setEdit({client_id:client?.id||'',kind:'meeting',title:'',start:day+'T09:00',end:day+'T10:00',member_ids:[],buffer_before:0,buffer_after:0,shared:true,location:'',notes:'',status:'scheduled'})}
 function open(e){setError('');setEdit({...e,start:localInput(e.starts_at),end:localInput(e.ends_at)})}
 async function save(e){e.preventDefault();setBusy(true);setError('');try{await request({action:'saveEvent',id:edit.id,event:{...edit,starts_at:brazilISO(edit.start),ends_at:brazilISO(edit.end)}});setEdit(null);await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
 const update=(key,value)=>setEdit(x=>({...x,[key]:value}));
 function eventButton(e){return <button key={e.id} className={'uxEvent '+e.kind} style={{borderLeftColor:color(e.client_id)}} onClick={()=>open(e)}><small>{EVENT_TYPES[e.kind]} {e.dateOnly?'· previsão':`· ${clock(e.starts_at)}`}</small><strong>{e.title||e.clients?.name||'Compromisso'}</strong><span>{e.clients?.name||'Interno'}</span></button>}
 return <section className="uxCalendar"><div className="sectionHead"><div><small>{client?'CALENDÁRIO DO CLIENTE':'AGENDA GERAL'}</small><h2>{client?`Programação · ${client.name}`:'Seu tempo, bem organizado.'}</h2><p>Reuniões, gravações e postagens em um só lugar. Horário de Brasília.</p></div>{data.agency&&<button className="primary" onClick={()=>newEvent()}>+ Novo compromisso</button>}</div><div className="uxFilters"><div className="uxSegment">{[['month','Mês'],['today','Hoje'],['week','Próximos 7 dias']].map(([k,l])=><button key={k} className={view===k?'active':''} onClick={()=>setView(k)}>{l}</button>)}</div><input aria-label="Mês" type="month" value={month} onChange={e=>{if(e.target.value){setMonth(e.target.value);setView('month')}}}/><select aria-label="Tipo" value={kind} onChange={e=>setKind(e.target.value)}><option value="">Todos os tipos</option>{Object.entries(EVENT_TYPES).map(([k,l])=><option key={k} value={k}>{l}</option>)}</select>{!client&&<select aria-label="Cliente" value={customer} onChange={e=>setCustomer(e.target.value)}><option value="">Todos os clientes</option>{data.clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select>}{data.agency&&<select aria-label="Responsável" value={member} onChange={e=>setMember(e.target.value)}><option value="">Toda a equipe</option>{data.team.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select>}</div><Notice error={error}/>{loading?<p role="status">Carregando agenda…</p>:view==='month'?<div className="uxCalendarScroll"><div className="calendarGrid">{['DOM','SEG','TER','QUA','QUI','SEX','SÁB'].map(d=><div key={d} className="weekday">{d}</div>)}{[...Array(first).fill(null),...Array.from({length:days},(_,i)=>i+1)].map((day,i)=>{const key=month+'-'+String(day).padStart(2,'0');return <div key={i} className={'calDay '+(key===today?'uxToday':'')}>{day&&<><div className="uxDayHead"><b>{day}</b>{data.agency&&<button aria-label={`Adicionar em ${day}`} onClick={()=>newEvent(key)}>+</button>}</div>{visible.filter(e=>e.dateOnly?dayKey(e.starts_at)===key:new Date(e.starts_at)<new Date(key+'T00:00:00-03:00').getTime()+86400000&&new Date(e.ends_at)>new Date(key+'T00:00:00-03:00')).map(eventButton)}</>}</div>})}</div></div>:<div className="uxAgendaList">{visible.map(e=><div key={e.id}><p>{new Date(e.starts_at).toLocaleDateString('pt-BR',{timeZone:'America/Sao_Paulo',weekday:'long',day:'2-digit',month:'long'})}</p>{eventButton(e)}</div>)}{!visible.length&&<div className="uxEmpty"><h3>Agenda livre neste período.</h3><p>Altere os filtros ou cadastre um compromisso.</p></div>}</div>}
 {edit&&<Dialog title={edit.id?'Detalhes do compromisso':'Novo compromisso'} onClose={()=>{if(!busy)setEdit(null)}}><form onSubmit={save}><fieldset disabled={busy||!data.agency||edit.fromContent} className="uxFieldset"><div className="formGrid"><label>Título<input required value={edit.title||''} onChange={e=>update('title',e.target.value)}/></label><label>Tipo<select value={edit.kind} onChange={e=>update('kind',e.target.value)}>{Object.entries(EVENT_TYPES).map(([k,l])=><option key={k} value={k}>{l}</option>)}</select></label><label>Cliente<select disabled={!!client} value={edit.client_id||''} onChange={e=>update('client_id',e.target.value)}><option value="">Compromisso interno</option>{data.clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Local ou link<input value={edit.location||''} onChange={e=>update('location',e.target.value)}/></label><label>Início<input required type="datetime-local" value={edit.start} onChange={e=>update('start',e.target.value)}/></label><label>Fim<input required type="datetime-local" value={edit.end} onChange={e=>update('end',e.target.value)}/></label>{edit.kind!=='post'&&<><label>Preparação antes (min)<input type="number" min="0" max="1440" value={edit.buffer_before} onChange={e=>update('buffer_before',+e.target.value)}/></label><label>Deslocamento após (min)<input type="number" min="0" max="1440" value={edit.buffer_after} onChange={e=>update('buffer_after',+e.target.value)}/></label></>}</div>{data.agency&&<><p>Responsáveis <small>· sem seleção, reserva toda a equipe</small></p><div className="uxActions">{data.team.map(m=><label key={m.id} className="checkLine"><input type="checkbox" checked={edit.member_ids?.includes(m.id)||false} onChange={e=>update('member_ids',e.target.checked?[...(edit.member_ids||[]),m.id]:(edit.member_ids||[]).filter(id=>id!==m.id))}/>{m.name}</label>)}</div></>}<label>Observações<textarea rows={4} value={edit.notes||''} onChange={e=>update('notes',e.target.value)}/></label>{edit.kind!=='block'&&<label className="checkLine"><input type="checkbox" checked={edit.shared} onChange={e=>update('shared',e.target.checked)}/>Visível para o cliente</label>}<label>Status<select value={edit.status} onChange={e=>update('status',e.target.value)}><option value="scheduled">Agendado</option><option value="cancelled">Cancelado</option></select></label></fieldset>{edit.fromContent?<p>Previsão vinculada a um conteúdo. Altere a data no card de produção. Não publica automaticamente nas redes.</p>:data.agency&&<button className="primary" disabled={busy}>{busy?'Verificando disponibilidade…':'Salvar compromisso'}</button>}<Notice error={error}/></form></Dialog>}
 </section>;
}
