import {PGlite} from '@electric-sql/pglite';
import {readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const db=new PGlite();
await db.exec(`
 create role anon;create role authenticated;create role service_role;
 create schema auth;create schema private;
 create table auth.users(id uuid primary key);
 create type public.app_role as enum('super_admin','agency_owner','agency_admin','team_member','client_user');
 create table public.organizations(id uuid primary key);
 create table public.organization_members(organization_id uuid,user_id uuid,role public.app_role,is_active boolean);
 create table public.clients(id uuid primary key,organization_id uuid,name text);
 create table public.agency_team_members(id uuid primary key,organization_id uuid,is_active boolean);
 create table public.client_users(client_id uuid,user_id uuid);
 create table public.demands(id uuid primary key default gen_random_uuid(),client_id uuid,organization_id uuid,title text,type text,briefing text,status text);
 create table public.demand_versions(id uuid primary key,demand_id uuid,status text);
 create table public.approval_events(id uuid primary key default gen_random_uuid(),demand_version_id uuid,user_id uuid,event text,note text);
 create table public.recording_sessions(id uuid primary key,organization_id uuid,client_id uuid not null,title text,starts_at timestamptz,ends_at timestamptz,location text,notes text,status text,created_by uuid,updated_at timestamptz default now());
 alter table public.recording_sessions enable row level security;
 create function public.is_super_admin() returns boolean language sql as 'select false';
 create function public.has_org_role(uuid,public.app_role[]) returns boolean language sql as 'select false';
 create function private.user_has_client_access(uuid) returns boolean language sql as 'select false';
 create function public.avesso_production_action(target_demand uuid,target_version uuid,actor_id uuid,action_name text,new_status text) returns text language plpgsql as $$
 begin
 if not exists(select 1 from public.client_users where client_id=(select client_id from public.demands where id=target_demand) and user_id=actor_id) then raise exception 'Permission denied';end if;
 update public.demand_versions set status=case when action_name='approve' then 'approved' else 'changes_requested' end where id=target_version;
 update public.demands set status=case when action_name='approve' then 'approved' else 'adjustments' end where id=target_demand;
 insert into public.approval_events(demand_version_id,user_id,event) values(target_version,actor_id,case when action_name='approve' then 'approved' else 'changes_requested' end);
 return case when action_name='approve' then 'approved' else 'adjustments' end;
 end;$$;
`);
const sql=await readFile(new URL('../../database/workspace-ux-setup.sql',import.meta.url),'utf8');
await db.exec(sql);console.log('PASS SQL migration compiles on PostgreSQL engine');
const productionSql=await readFile(new URL('../../database/production-projects-setup.sql',import.meta.url),'utf8');
await db.exec(productionSql);console.log('PASS production project schema and approval-date trigger compile');
const id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const [org,actor,client,member,otherMember,linkedUser]=[1,2,3,4,5,6].map(id);
await db.query('insert into auth.users values ($1),($2)',[actor,linkedUser]);
await db.query('insert into public.organizations values ($1)',[org]);
await db.query("insert into public.organization_members values ($1,$2,'agency_owner',true),($1,$3,'client_user',true)",[org,actor,linkedUser]);
await db.query("insert into public.clients values ($1,$2,'Teste local')",[client,org]);
await db.query('insert into public.client_users values ($1,$2)',[client,linkedUser]);
await db.query('insert into public.agency_team_members values ($1,$3,true),($2,$3,true)',[member,otherMember,org]);
const payload={title:'Gravação',kind:'recording',starts_at:'2026-10-06T13:00Z',ends_at:'2026-10-06T14:00Z',member_ids:[member],buffer_before:0,buffer_after:0,status:'scheduled',shared:true};
const save=(p,event=null,who=actor)=>db.query('select public.avesso_save_calendar_event($1,$2,$3,$4,$5)',[who,org,event,client,JSON.stringify(p)]);
const event=(await save(payload)).rows[0].avesso_save_calendar_event;
await assert.rejects(save(payload),/Conflito/);
await save({...payload,member_ids:[otherMember]});
await save({...payload,kind:'post'});
await save({...payload,starts_at:'2026-10-06T14:00Z',ends_at:'2026-10-06T15:00Z'});
await assert.rejects(save({...payload,starts_at:'2026-10-06T15:00Z',ends_at:'2026-10-06T16:00Z',buffer_before:15}),/Conflito/);
await assert.rejects(save({...payload,status:'cancelled'},null,linkedUser),/Permission denied/);
await save({...payload,status:'cancelled'},event);
await save(payload);
console.log('PASS actual SQL conflict, independent teams, adjacent slots, buffers, cancelled events and portal permissions');
const ref=(await db.query("insert into public.client_materials(client_id,section,title,body,author_id) values ($1,'references','Ideia','Só texto',$2) returning id",[client,actor])).rows[0].id;
const convert=()=>db.query('select public.avesso_reference_to_content($1,$2)',[actor,ref]);
const demand=(await convert()).rows[0].avesso_reference_to_content;
const project=(await db.query("insert into public.production_projects(organization_id,client_id,title,created_by) values ($1,$2,'Campanha de teste',$3) returning id",[org,client,actor])).rows[0].id;
await db.query('update public.demands set project_id=$1 where id=$2',[project,demand]);
assert.equal((await db.query('select project_id from public.demands where id=$1',[demand])).rows[0].project_id,project);
assert.equal((await convert()).rows[0].avesso_reference_to_content,demand);
assert.equal((await db.query('select count(*)::int as n from public.client_material_history')).rows[0].n,1);
await db.query("update public.demands set status='with_client' where id=$1",[demand]);
const version=id(7);await db.query("insert into public.demand_versions(id,demand_id,status) values ($1,$2,'sent_for_review')",[version,demand]);
const review=(who,note)=>db.query("select public.avesso_review_with_note($1,$2,$3,'changes',$4)",[demand,version,who,note]);
await assert.rejects(review(linkedUser,''),/Descreva/);
await assert.rejects(review(actor,'Ajuste'),/Permission denied/);
assert.equal((await db.query('select status from public.demand_versions where id=$1',[version])).rows[0].status,'sent_for_review');
await review(linkedUser,'Trocar a foto');
assert.equal((await db.query('select body from public.client_notes')).rows[0].body,'Trocar a foto');
await db.query("update public.demands set status='approved' where id=$1",[demand]);
assert.ok((await db.query('select approved_at from public.demands where id=$1',[demand])).rows[0].approved_at);
await assert.rejects(review(linkedUser,'Outra decisão'),/não está mais/);
console.log('PASS text history, idempotent reference conversion and atomic review with mandatory note');
const perms=await db.query("select tablename from pg_tables where schemaname='public' and tablename in ('client_materials','client_notes','client_assets','client_material_history') and rowsecurity");assert.equal(perms.rows.length,4);
await db.exec('set role authenticated');
await assert.rejects(db.query('select * from public.client_materials'),/permission denied/);
await assert.rejects(db.query('select public.avesso_reference_to_content($1,$2)',[actor,ref]),/permission denied/);
console.log('PASS new tables and privileged RPCs deny direct authenticated access');
await db.close();
