'use client';
import {useEffect,useState} from 'react';
import {createClient} from '@supabase/supabase-js';
import {LayoutDashboard,Zap,Users,PanelsTopLeft,CircleCheckBig,CalendarDays,DollarSign,UserRoundCog,Settings,Bell,Search,ArrowUpRight,Menu,X,LogOut,FolderOpen,PackageCheck,FileText,WalletCards,Clapperboard,ChevronLeft,Plus,Save,Trash2,Pencil,Clock3} from 'lucide-react';

const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL,process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY||process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY);
const agencyNav=[['Visão geral',LayoutDashboard],['Comando',Zap],['Clientes',Users],['Produção',PanelsTopLeft],['Aprovações',CircleCheckBig],['Calendário',CalendarDays],['Financeiro',DollarSign],['Equipe',UserRoundCog]];
const clientNav=[['Início',LayoutDashboard],['Aprovações',CircleCheckBig],['Calendário',CalendarDays],['Entregas',PackageCheck],['Arquivos',FolderOpen]];

export default function Page(){
 const [session,setSession]=useState(undefined),[ctx,setCtx]=useState(null),[error,setError]=useState('');
 useEffect(()=>{supabase.auth.getSession().then(({data})=>setSession(data.session));const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>subscription.unsubscribe()},[]);
 useEffect(()=>{if(!session){setCtx(null);return} loadContext(session.user.id).then(setCtx).catch(e=>setError(e.message))},[session]);
 if(session===undefined)return <Splash/>; if(!session)return <Login onError={setError} error={error}/>; if(!ctx)return <Splash text={error||'Preparando seu ambiente...'}/>;
 return ctx.role==='client_user'?<ClientPortal ctx={ctx}/>:<AgencyApp ctx={ctx}/>;
}
async function loadContext(userId){
 const {data:profile}=await supabase.from('profiles').select('full_name').eq('id',userId).single();
 const {data:memberships,error:mErr}=await supabase.from('organization_members').select('role, organization_id, organizations(id,name,slug)').eq('user_id',userId).eq('is_active',true).limit(1);if(mErr)throw mErr;
 const m=memberships?.[0];if(!m)throw new Error('Seu usuário ainda não está vinculado a uma organização.');
 let client=null;if(m.role==='client_user'){const {data,error}=await supabase.from('client_users').select('clients(id,name,slug,status)').eq('user_id',userId).limit(1);if(error)throw error;client=data?.[0]?.clients||null;}
 return {name:profile?.full_name||'Usuário',role:m.role,organization:m.organizations,client};
}
function Login({error,onError}){const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false);async function submit(e){e.preventDefault();setBusy(true);onError('');const {error}=await supabase.auth.signInWithPassword({email,password});if(error)onError(error.message==='Invalid login credentials'?'E-mail ou senha incorretos.':error.message);setBusy(false)}return <main className="loginPage"><section className="loginBrand"><div className="brand big">AVESSO<span>.</span></div><h1>A operação por trás<br/>da criação.</h1><p>Clientes, produção, aprovação e operação no mesmo lugar.</p></section><section className="loginBox"><div className="loginCard"><small>ACESSO AVESSO</small><h2>Entre no seu espaço.</h2><p>O ambiente é definido automaticamente pelo seu perfil.</p><form onSubmit={submit}><label>E-mail<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Senha<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label>{error&&<div className="loginError">{error}</div>}<button className="loginBtn" disabled={busy}>{busy?'Entrando...':'Entrar no AVESSO →'}</button></form></div></section></main>}

function AgencyApp({ctx}){const [active,setActive]=useState('Visão geral'),[mobile,setMobile]=useState(false),[selectedClient,setSelectedClient]=useState(null),[clientTab,setClientTab]=useState('Visão geral');
 function nav(name){setSelectedClient(null);setActive(name)}
 return <main className="shell"><Sidebar nav={agencyNav} active={selectedClient?'Clientes':active} setActive={nav} mobile={mobile} setMobile={setMobile} org={ctx.organization?.name}/><section className="content"><Top ctx={ctx} mobile={mobile} setMobile={setMobile} eyebrow={selectedClient?'CLIENTE 360°':active.toUpperCase()} subtitle={selectedClient?`Tudo de ${selectedClient.name} em um só lugar.`:'A operação por trás da criação.'}/>{selectedClient?<Client360 client={selectedClient} ctx={ctx} tab={clientTab} setTab={setClientTab} onBack={()=>setSelectedClient(null)}/>:<AgencyModule active={active} ctx={ctx} onClient={c=>{setSelectedClient(c);setClientTab('Visão geral')}}/>}</section></main>}
function AgencyModule({active,ctx,onClient}){if(active==='Clientes')return <ClientsPage ctx={ctx} onClient={onClient}/>;if(active==='Visão geral')return <Overview/>;return <EmptyModule name={active}/>}
function Overview(){return <><div className="metrics"><article className="metric"><small>CLIENTES</small><strong>—</strong><span>dados reais em implantação</span></article><article className="metric"><small>EM PRODUÇÃO</small><strong>—</strong><span>módulo preparado</span></article><article className="metric"><small>APROVAÇÕES</small><strong>—</strong><span>módulo preparado</span></article></div><article className="startCard"><small>AVESSO V6</small><h2>Cliente 360° agora é operacional.</h2><p>Abra <b>Clientes</b>, entre no Cervejando com Diego e configure contrato e escopo diretamente pelo painel.</p></article></>}
function EmptyModule({name}){return <div className="emptyModule"><div className="emptyIcon">+</div><small>MÓDULO {name.toUpperCase()}</small><h2>{name}</h2><p>A navegação já está ativa. Os dados operacionais deste módulo serão conectados nas próximas etapas.</p></div>}
function ClientsPage({ctx,onClient}){
 const [clients,setClients]=useState([]),[loading,setLoading]=useState(true),[err,setErr]=useState(''),[showNew,setShowNew]=useState(false);
 async function load(){setLoading(true);const {data,error}=await supabase.from('clients').select('id,name,slug,status,organization_id,contact_name,contact_email,whatsapp,instagram,website,portal_access_status').eq('organization_id',ctx.organization.id).order('name');if(error)setErr(error.message);else setClients(data||[]);setLoading(false)}
 useEffect(()=>{load()},[ctx.organization.id]);
 return <section className="module"><div className="moduleHead"><div><small>CARTEIRA</small><h2>Clientes</h2><p>Cadastre, abra e administre cada cliente sem sair do AVESSO.</p></div><button className="primary" onClick={()=>setShowNew(true)}><Plus size={16}/> Novo cliente</button></div>{loading?<p>Carregando...</p>:err?<div className="loginError">{err}</div>:clients.length?<div className="clientCards">{clients.map(c=><button className="clientCard" key={c.id} onClick={()=>onClient(c)}><div className="clientInitial">{c.name[0]}</div><div><span className="statusDot"/> <small>{c.status==='active'?'ATIVO':c.status.toUpperCase()}</small><h3>{c.name}</h3><p>Abrir Cliente 360°</p></div><ArrowUpRight/></button>)}</div>:<div className="emptyModule compact"><small>CARTEIRA VAZIA</small><h2>Seu próximo cliente começa aqui.</h2><p>Clique em “Novo cliente” para criar o Cliente 360°.</p></div>}{showNew&&<NewClientModal ctx={ctx} onClose={()=>setShowNew(false)} onCreated={async c=>{setShowNew(false);await load();onClient(c)}}/>}</section>}
function slugify(v){return v.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'')}
function NewClientModal({ctx,onClose,onCreated}){
 const [form,setForm]=useState({name:'',legal_name:'',status:'active',contact_name:'',contact_email:'',whatsapp:'',instagram:'',website:'',notes:'',portal:false,portal_email:''}),[saving,setSaving]=useState(false),[err,setErr]=useState('');
 function f(k,v){setForm(x=>({...x,[k]:v}))}
 async function submit(e){e.preventDefault();setSaving(true);setErr('');let base=slugify(form.name)||'cliente',slug=base,n=2;while(true){const {data}=await supabase.from('clients').select('id').eq('organization_id',ctx.organization.id).eq('slug',slug).maybeSingle();if(!data)break;slug=`${base}-${n++}`}
  const payload={organization_id:ctx.organization.id,name:form.name.trim(),legal_name:form.legal_name||null,slug,status:form.status,contact_name:form.contact_name||null,contact_email:form.contact_email||null,whatsapp:form.whatsapp||null,instagram:form.instagram||null,website:form.website||null,notes:form.notes||null,portal_email:form.portal?form.portal_email||form.contact_email||null:null,portal_access_status:form.portal?'pending':'not_requested'};
  const {data,error}=await supabase.from('clients').insert(payload).select('id,name,slug,status,organization_id').single();if(error){setErr(error.message);setSaving(false);return}
  const {error:ce}=await supabase.from('contracts').insert({client_id:data.id,organization_id:ctx.organization.id,status:'defining'});if(ce){setErr('Cliente criado, mas o contrato inicial não pôde ser criado: '+ce.message);setSaving(false);return}onCreated(data)
 }
 return <div className="modalBackdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><form className="modalCard" onSubmit={submit}><div className="modalHead"><div><small>NOVO CLIENTE</small><h2>Criar Cliente 360°</h2><p>Os dados podem ser completados ou alterados depois.</p></div><button type="button" className="modalClose" onClick={onClose}><X size={20}/></button></div><div className="formGrid"><label>Nome do cliente *<input required autoFocus value={form.name} onChange={e=>f('name',e.target.value)} placeholder="Ex.: Cervejando com Diego"/></label><label>Empresa / razão social<input value={form.legal_name} onChange={e=>f('legal_name',e.target.value)} placeholder="Opcional"/></label><label>Status<select value={form.status} onChange={e=>f('status',e.target.value)}><option value="active">Ativo</option><option value="paused">Pausado</option></select></label><label>Contato principal<input value={form.contact_name} onChange={e=>f('contact_name',e.target.value)} placeholder="Nome da pessoa"/></label><label>E-mail<input type="email" value={form.contact_email} onChange={e=>f('contact_email',e.target.value)} placeholder="cliente@email.com"/></label><label>WhatsApp<input value={form.whatsapp} onChange={e=>f('whatsapp',e.target.value)} placeholder="(16) 99999-9999"/></label><label>Instagram<input value={form.instagram} onChange={e=>f('instagram',e.target.value)} placeholder="@cliente"/></label><label>Site<input value={form.website} onChange={e=>f('website',e.target.value)} placeholder="https://..."/></label><label className="wide">Observações<textarea value={form.notes} onChange={e=>f('notes',e.target.value)} placeholder="Informações importantes sobre o cliente..."/></label></div><div className="portalChoice"><label className="checkLine"><input type="checkbox" checked={form.portal} onChange={e=>f('portal',e.target.checked)}/><span><b>Preparar acesso ao Portal do Cliente</b><small>O cliente será marcado como acesso pendente. A ativação do login será feita na etapa de convite seguro.</small></span></label>{form.portal&&<label>E-mail para acesso<input type="email" value={form.portal_email} onChange={e=>f('portal_email',e.target.value)} placeholder={form.contact_email||'cliente@email.com'}/></label>}</div>{err&&<div className="loginError">{err}</div>}<div className="modalActions"><button type="button" className="secondary" onClick={onClose}>Cancelar</button><button className="primary" disabled={saving}><Plus size={16}/>{saving?'Criando...':'Criar cliente'}</button></div></form></div>
}

const tabs=['Visão geral','Produção','Aprovações','Calendário','Entregas','Financeiro','Contrato e escopo','Arquivos'];
function Client360({client,ctx,tab,setTab,onBack}){return <section className="client360"><button className="back" onClick={onBack}><ChevronLeft size={16}/> Clientes</button><div className="clientTitle"><div className="clientInitial bigInitial">{client.name[0]}</div><div><small>CLIENTE ATIVO</small><h2>{client.name}</h2><p>Cliente 360° · {ctx.organization.name}</p></div></div><div className="tabs">{tabs.map(t=><button type="button" className={tab===t?'active':''} key={t} onClick={()=>setTab(t)}>{t}</button>)}</div>{tab==='Visão geral'?<ClientHome setTab={setTab}/>:tab==='Contrato e escopo'?<ContractScope client={client} ctx={ctx}/>:<ClientSubpage tab={tab} client={client}/>}</section>}
function ClientHome({setTab}){const cards=[['Produção','Demandas e andamento',Clapperboard],['Aprovações','Materiais aguardando cliente',CircleCheckBig],['Calendário','Planejamento editorial',CalendarDays],['Entregas','Histórico entregue',PackageCheck],['Financeiro','Mensalidades e adicionais',WalletCards],['Contrato e escopo','Pacote, limites e extras',FileText],['Arquivos','Materiais do cliente',FolderOpen]];return <><div className="notice"><Clock3 size={18}/><div><b>Escopo em definição</b><span>Você pode deixar quantidades e valores como “A definir” e completar depois da reunião.</span></div></div><div className="hubCards">{cards.map(([title,desc,I])=><button type="button" key={title} onClick={()=>setTab(title)}><I size={21}/><div><h3>{title}</h3><p>{desc}</p></div><ArrowUpRight size={17}/></button>)}</div></>}
function ClientSubpage({tab,client}){return <div className="emptyModule compact"><small>{client.name.toUpperCase()}</small><h2>{tab}</h2><p>Área já navegável e vinculada a este cliente. A estrutura de dados deste módulo entra na próxima etapa.</p></div>}
function ContractScope({client,ctx}){const [contract,setContract]=useState(null),[items,setItems]=useState([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[msg,setMsg]=useState('');
 useEffect(()=>{load()},[client.id]);async function load(){setLoading(true);const {data,error}=await supabase.from('contracts').select('*').eq('client_id',client.id).order('created_at',{ascending:false}).limit(1).maybeSingle();if(error){setMsg(error.message);setLoading(false);return}let ct=data;if(!ct){const ins=await supabase.from('contracts').insert({client_id:client.id,organization_id:ctx.organization.id,status:'defining'}).select().single();ct=ins.data;if(ins.error)setMsg(ins.error.message)}setContract(ct);if(ct){const {data:its}=await supabase.from('contract_items').select('*').eq('contract_id',ct.id).order('sort_order');setItems(its||[])}setLoading(false)}
 function c(k,v){setContract(x=>({...x,[k]:v}))}function i(id,k,v){setItems(x=>x.map(a=>a.id===id?{...a,[k]:v}:a))}
 async function save(){setSaving(true);setMsg('');const payload={status:contract.status,monthly_value:blankNum(contract.monthly_value),start_date:contract.start_date||null,end_date:contract.end_date||null,due_day:blankNum(contract.due_day),notes:contract.notes||null};const {error}=await supabase.from('contracts').update(payload).eq('id',contract.id);if(error){setMsg(error.message);setSaving(false);return}for(const item of items){const {error:e}=await supabase.from('contract_items').update({name:item.name,monthly_quantity:blankNum(item.monthly_quantity),extra_value:blankNum(item.extra_value),is_active:item.is_active,sort_order:item.sort_order}).eq('id',item.id);if(e){setMsg(e.message);setSaving(false);return}}setMsg('Alterações salvas.');setSaving(false)}
 async function add(){const {data,error}=await supabase.from('contract_items').insert({contract_id:contract.id,name:'Novo serviço',monthly_quantity:null,extra_value:null,is_active:true,sort_order:items.length}).select().single();if(error)setMsg(error.message);else setItems(x=>[...x,data])}
 async function remove(id){await supabase.from('contract_items').delete().eq('id',id);setItems(x=>x.filter(a=>a.id!==id))}
 if(loading)return <p>Carregando contrato...</p>;if(!contract)return <div className="loginError">{msg||'Não foi possível abrir o contrato.'}</div>;
 return <div className="contractWrap"><div className="sectionHead"><div><small>CONFIGURAÇÃO OPERACIONAL</small><h3>Contrato</h3><p>Campos vazios permanecem como “A definir”.</p></div><button className="primary" onClick={save} disabled={saving}><Save size={16}/>{saving?'Salvando...':'Salvar alterações'}</button></div><div className="formGrid"><label>Status<select value={contract.status} onChange={e=>c('status',e.target.value)}><option value="defining">Em definição</option><option value="active">Ativo</option><option value="paused">Pausado</option><option value="ended">Encerrado</option></select></label><label>Valor mensal (R$)<input type="number" placeholder="A definir" value={contract.monthly_value??''} onChange={e=>c('monthly_value',e.target.value)}/></label><label>Início<input type="date" value={contract.start_date||''} onChange={e=>c('start_date',e.target.value)}/></label><label>Término<input type="date" value={contract.end_date||''} onChange={e=>c('end_date',e.target.value)}/></label><label>Dia do vencimento<input type="number" min="1" max="31" placeholder="A definir" value={contract.due_day??''} onChange={e=>c('due_day',e.target.value)}/></label><label className="wide">Observações<textarea placeholder="Condições, detalhes comerciais, acordos..." value={contract.notes||''} onChange={e=>c('notes',e.target.value)}/></label></div><div className="scopeHead"><div><small>ESCOPO MENSAL</small><h3>Entregas contratadas</h3></div><button className="secondary" onClick={add}><Plus size={15}/> Adicionar serviço</button></div><div className="scopeTable"><div className="scopeRow scopeLabels"><span>ATIVO</span><span>ENTREGA</span><span>QTD. MENSAL</span><span>VALOR EXTRA</span><span/></div>{items.map(item=><div className="scopeRow" key={item.id}><label className="switch"><input type="checkbox" checked={item.is_active} onChange={e=>i(item.id,'is_active',e.target.checked)}/><i/></label><input value={item.name} onChange={e=>i(item.id,'name',e.target.value)}/><input type="number" min="0" placeholder="A definir" value={item.monthly_quantity??''} onChange={e=>i(item.id,'monthly_quantity',e.target.value)}/><input type="number" min="0" step="0.01" placeholder="A definir" value={item.extra_value??''} onChange={e=>i(item.id,'extra_value',e.target.value)}/><button className="iconDanger" onClick={()=>remove(item.id)} title="Remover"><Trash2 size={16}/></button></div>)}</div>{msg&&<div className={msg==='Alterações salvas.'?'saveMsg':'loginError'}>{msg}</div>}<div className="ruleNote"><b>Regra AVESSO:</b> quantidade vazia = <b>A definir</b>. Somente uma entrega marcada como <b>Entregue</b> consumirá o pacote mensal.</div></div>}
function blankNum(v){return v===''||v===null||v===undefined?null:Number(v)}

function ClientPortal({ctx}){const [active,setActive]=useState('Início'),[mobile,setMobile]=useState(false);return <main className="shell clientShell"><Sidebar nav={clientNav} active={active} setActive={setActive} mobile={mobile} setMobile={setMobile} org={ctx.client?.name||'Meu espaço'} client/><section className="content"><Top ctx={ctx} mobile={mobile} setMobile={setMobile} eyebrow="PORTAL DO CLIENTE" subtitle={`Seu espaço na ${ctx.organization?.name||'agência'}.`}/><div className="clientWelcome"><div><small>SEU ESPAÇO</small><h2>{ctx.client?.name}</h2><p>Produção, aprovações, calendário e entregas.</p></div><div className="clientBadge">CLIENTE</div></div><EmptyModule name={active}/><div className="privacyNote">Você está vendo apenas informações vinculadas a <b>{ctx.client?.name}</b>.</div></section></main>}
function Sidebar({nav,active,setActive,mobile,setMobile,org,client}){return <aside className={mobile?'side open':'side'}><div className="brand">AVESSO<span>.</span></div><div className="tag">{client?'SEU ESPAÇO\nCRIATIVO.':'A OPERAÇÃO\nPOR TRÁS\nDA CRIAÇÃO.'}</div><nav>{nav.map(([n,I])=><button key={n} className={active===n?'active':''} onClick={()=>{setActive(n);setMobile(false)}}><I size={19}/><span>{n}</span></button>)}</nav><div className="org"><span className="dot"/><div><small>{client?'CLIENTE':'ORGANIZAÇÃO'}</small><strong>{org}</strong></div></div>{!client&&<button className="settings"><Settings size={18}/>Configurações</button>}<button className="logout" onClick={()=>supabase.auth.signOut()}><LogOut size={17}/>Sair</button><div className="version">V 0.6.0 · CLIENTES</div></aside>}
function Top({ctx,mobile,setMobile,eyebrow,subtitle}){return <header><button className="hamb" onClick={()=>setMobile(!mobile)}>{mobile?<X/>:<Menu/>}</button><div><div className="eyebrow">{eyebrow}</div><h1>Olá, <strong>{ctx.name}.</strong></h1><p>{subtitle}</p></div><div className="tools"><div className="search"><Search size={17}/><span>Buscar no AVESSO...</span></div><button className="bell"><Bell size={18}/></button><div className="avatar">{ctx.name?.[0]?.toUpperCase()}</div></div></header>}
function Splash({text='Carregando AVESSO...'}){return <main className="splash"><div className="brand big">AVESSO<span>.</span></div><p>{text}</p></main>}
