'use client';
import {useState} from 'react';
import {LayoutDashboard,Zap,Users,PanelsTopLeft,CircleCheckBig,CalendarDays,DollarSign,UserRoundCog,Settings,Bell,Search,ArrowUpRight,Clock3,WalletCards,Layers3,Menu,X} from 'lucide-react';
const nav=[['Visão geral',LayoutDashboard],['Comando',Zap],['Clientes',Users],['Produção',PanelsTopLeft],['Aprovações',CircleCheckBig],['Calendário',CalendarDays],['Financeiro',DollarSign],['Equipe',UserRoundCog]];
const metrics=[['Clientes ativos','12','+2 este mês'],['Demandas em aberto','27','4 atrasadas'],['Em produção','14','6 revisão · 7 cliente'],['Aprovações pendentes','6','2 há mais de 3 dias'],['A receber','R$ 7.450','R$ 2.500 vencidos'],['Custos do mês','R$ 3.840','setembro']];
export default function Page(){const [active,setActive]=useState('Visão geral'); const [mobile,setMobile]=useState(false);return <main className="shell">
<aside className={mobile?'side open':'side'}><div className="brand">AVESSO<span>.</span></div><div className="tag">A OPERAÇÃO<br/>POR TRÁS<br/>DA CRIAÇÃO.</div><nav>{nav.map(([n,I])=><button key={n} className={active===n?'active':''} onClick={()=>{setActive(n);setMobile(false)}}><I size={19}/><span>{n}</span>{n==='Aprovações'&&<b>2</b>}</button>)}</nav><div className="org"><span className="dot"/><div><small>ORGANIZAÇÃO</small><strong>Desvio</strong></div></div><button className="settings"><Settings size={18}/>Configurações</button><div className="version">V 0.1.0</div></aside>
<section className="content"><header><button className="hamb" onClick={()=>setMobile(!mobile)}>{mobile?<X/>:<Menu/>}</button><div><div className="eyebrow">CENTRAL DE COMANDO</div><h1>Bom dia, <strong>Natalia.</strong></h1><p>Aqui está o que precisa da sua atenção hoje.</p></div><div className="tools"><div className="search"><Search size={17}/><span>Buscar no AVESSO...</span><kbd>⌘ K</kbd></div><button className="bell"><Bell size={18}/><i/></button><div className="avatar">N</div></div></header>
<div className="metrics">{metrics.map((m,i)=><article className="metric" key={m[0]}><small>{m[0]}</small><strong>{m[1]}</strong><span className={i===3||i===4?'danger':''}>{m[2]}</span></article>)}</div>
<div className="heroGrid"><article className="money"><div><label>DINHEIRO QUE PODE ESTAR ESCAPANDO</label><h2><em>R$ 530</em> em adicionais<br/>ainda não cobrados.</h2></div><div className="extras"><p><b>Cervejando com Diego</b><span>Reel adicional <strong>R$ 350</strong></span></p><p><b>Grudo</b><span>Carrossel adicional <strong>R$ 180</strong></span></p><button>Ver adicionais <ArrowUpRight size={16}/></button></div></article><article className="scope"><small>+ &nbsp; ESCOPO</small><h3>Cervejando atingiu <b>100%</b><br/>dos vídeos contratados.</h3><strong>4 / 4 vídeos</strong><p>Existe mais um Reel em briefing.<br/>Possível adicional: <b>R$ 350</b></p><button>Ver demanda →</button></article></div>
<div className="grid"><Card title="3 entregas vencem hoje." label="AGORA" tone="red" rows={['Reel — IPA Oktober','Carrossel — Residencial','Post — Nostalgia']}/><Card title="2 clientes ainda não responderam." label="APROVAÇÃO TRAVANDO PRODUÇÃO" tone="yellow" rows={['Cervejando com Diego · 3 dias','Essência Zen · 5 dias']}/><Card title="R$ 4.850 a receber." label="FINANCEIRO" rows={['Essência Zen · R$ 2.500','Grudo · R$ 2.180']}/><Card title="4 demandas sem movimentação há mais de 5 dias." label="DEMANDAS SEM ATIVIDADE" tone="orange" rows={['Vídeo institucional · Venere','Reel — Bastidores · Cervejando','Carrossel — Tipos de pele · Essência']}/><Card title="Concentração de demandas." label="EQUIPE" rows={['Lucas · 12 abertas','Maria · 8 abertas','João · 5 abertas']}/><Card title="3 cobranças chegando." label="CUSTOS DA OPERAÇÃO" rows={['CapCut Pro · R$ 49,90','IA · R$ 100,00','Armazenamento · R$ 59,90']}/></div>
<div className="clientHealth"><div><small>SAÚDE DOS CLIENTES</small><h3>Visão rápida da operação.</h3></div>{['Cervejando com Diego','Venere Arquitetura','Essência Zen','Grudo'].map((c,i)=><article key={c}><b>{c}</b><span>● {i===2?'Pagamento vencido':'Financeiro em dia'}</span><span>● {i===0?'Pacote de vídeos esgotado':'Escopo acompanhado'}</span></article>)}</div>
</section></main>}
function Card({title,label,rows,tone=''}){return <article className="card"><div className={'label '+tone}>{label}</div><h3>{title}</h3>{rows.map((r,i)=><div className="row" key={r}><span className="thumb">{i+1}</span><b>{r}</b><ArrowUpRight size={15}/></div>)}</article>}
